// automatically generated by the FlatBuffers compiler, do not modify

export { GameState, GameStateT } from './game-state/game-state.js';
export { MessageType } from './game-state/message-type.js';
export { Player, PlayerT } from './game-state/player.js';
export { Vec2, Vec2T } from './game-state/vec2.js';
